FriendlyCaptcha/friendly-challenge

docs/api.md
As discussed in #11, here is a PR for my React version. Feel free to adapt/change it as you like.
=> Add example code for React

src/localization.ts
Hi,
for our open source project, we are using weblate, it makes it way easier --- and brought a lot of volunteers translating into their languages. You should try for friendly captcha too ;)
=> Translation to french

README.md, docs/changelog.md, package-lock.json, package.json, src/captcha.ts, src/headless.ts, src/html/index.html, src/styles.css
This adds headless browser detection. Note that this can be circumvented by inventive attackers, but it adds another hurdle at no cost to real users.
=> Feature: headless browser detection

docs/widget_api.md, src/localization.ts
=> Added Portuguese language

docs/installation.md, docs/widget_api.md
This PR adds an example on how to use the Widget API in Vue using the composition API. It's very similar to the React example.
I also fixed two links in the docs which didn't point to the correct page.
=> Vue example & minor link fixes

src/captcha.ts
See https://github.com/FriendlyCaptcha/friendly-challenge/issues/81
=> Attach widget instance to Widget DOM element

src/localization.ts
=> Add Russian translation

LICENSE.md, docs/browser_support.md, docs/changelog.md, package-lock.json, package.json, src/dom.ts, src/localization.ts
Improved the accessibility of the widget for users using screen readers, there is now a localized, semantic title when the widget is completed stating *"Automatic spam check completed"*. This makes understanding what is going on easier for those who can not see the checkmark symbol.
Two minor unrelated chores also performed here:
* Bumped the version of some dependencies
* Removed unused commands and bumped the year range in the license.
=> Semantic title for SVG element for better accessibility

src/index.ts
Fixes #109.
The built d.ts file now looks like this:
```typescript
interface Localization {
text_init: string;
text_ready: string;
button_start: string;
text_fetching: string;
text_solving: string;
text_completed: string;
text_completed_sr: string;
text_expired: string;
button_restart: string;
text_error: string;
button_retry: string;
text_fetch_error: string;
}
declare const localizations: {
en: Localization;
de: Localization;
nl: Localization;
fr: Localization;
it: Localization;
pt: Localization;
es: Localization;
ca: Localization;
ja: Localization;
da: Localization;
ru: Localization;
sv: Localization;
};
interface WidgetInstanceOptions {
/**
* Don't set this to true unless you want to see what the experience is like for people using very old browsers.
* This does not increase security. …
```
=> Add additional exports to TS decl file (notably WidgetInstanceOptions)

docs/widget_api.md
=> Add svelte example

docs/widget_api.md, src/localization.ts
EL, UK, BG, CS, SK, NO, FI, LV, LT, PL, ET, HR, SR, SL, HU, RO
Thanks to @Tubilopto for providing the translations!
I wasn't sure which language / country code standard we are using, so I went with ISO639-1. 
closes #120
=> Add new localizations

src/localization.ts
=> Update swedish and danish translations

src/localization.ts
=> Add language code NB as any alias for NO

src/localization.ts
Seems like your are using ISO 639-1 language codes. I added Simplified Chinese translation regardless of other variants.
=> Add Chinese language

docs/installation.md
Hey,
a short note to the EU endpoint would be very useful, when reading the installation docs.
Hopefully this commit will save some time for others, when they get a 403 error response.
Best regards.
=> Adding note to EU endpoint to installation doc.

docs/browser_support.md, docs/changelog.md, docs/flutter.md, docs/installation.md, package-lock.json, package.json, src/headless.ts, src/puzzle.ts
=> Relax PluginArray prototype headless check, bump to version 0.9.8

docs/_sidebar.md, docs/openapi_spec.md, docs/openapiv3.json, docs/swagger.json
New `OpenAPI Spec` page under `Advanced` includes links OpenAPI `v2` and `v3` JSON files.
=> Add OpenApi spec to docs

docs/browser_support.md, docs/changelog.md, docs/flutter.md, docs/installation.md, docs/legacy_endpoint.md, docs/widget_api.md, package-lock.json, package.json, src/localization.ts, src/puzzle.ts
* Adds Chinese (traditional) and Vietnamese localizations.
* Bumps friendly-pow to version 0.2.2, which contains the fix for NextJS prod builds (fixes #165)
=> Release 0.9.9

docs/browser_support.md, docs/changelog.md, docs/flutter.md, docs/installation.md, docs/legacy_endpoint.md, package-lock.json, package.json, src/puzzle.ts
Release 0.9.11
@zcserei ping :)
Closes #183
=> Prepare for 0.9.11 release

docs/changelog.md, src/dom.ts
I decided to change it to a data- attribute so one can still see the info in the devtools.
closes #196
=> Remove debug title during solving

src/captcha.ts, src/html/index.html
Helps fix #200, this now exposes a `loadLanguage()` function that allows one to switch to a new language.
=> Support setting language dynamically

docs/widget_api.md
Hi there. I noticed that Vue.js example is slightly off. No styling, broken functionality.
This PR fixes that by adding missing attributes to the container element.
=> Add proper class and data attribute to Vue.js example

docs/browser_support.md, docs/csp.md, docs/flutter.md, docs/installation.md, docs/legacy_endpoint.md, src/puzzle.ts
Release 0.9.13
Use latest version in docs.
=> Update version references for 0.9.13 release

docs/changelog.md, src/localization.ts
=> Tweak French localization

docs/browser_support.md, docs/changelog.md, docs/csp.md, docs/flutter.md, docs/installation.md, docs/legacy_endpoint.md, docs/widget_api.md, package-lock.json, package.json, src/dom.ts, src/html/index.html, src/localization.ts, src/puzzle.ts, src/styles.css
Adds proper support for RTL (*right-to-left*) languages, and support for Hebrew and Thai.
Closes #232.
=> RTL support, Hebrew and Thai localizations, prepare for release 0.9.14

docs/changelog.md, docs/widget_api.md, src/localization.ts
=> Add KR locale

src/localization.ts
Hi,
I added Arabic localization and also added a forgotten semi-colon on the last update.
=> Add Arabic localization

docs/installation.md
- Made the Javascript self-hosted part a bigger heading.
- Added the "recommended by GDPR" description.
- Made the Update reminder bold for better visibility.
=> Update the Javascript GDPR description
