src/headless.ts
src/main.ts

Fixes https://github.com/FriendlyCaptcha/friendly-challenge/issues/26
1. convert for of Loop into classic for Loop for IE11 compatibility
2. NavigatorLanguage.languages is not supported in IE11
Fixes the non-working issues expierenced in v0.8.1
Tested with Chrome 88, Firefox 86, Safari 14 and IE 11
IE11 performance is still very poor due to Web Assembly missing :-(

Fix #26 IE11 for loops and unsupported feature NavigatorLanguage.languages

---

docs/browser_support.md
docs/changelog.md
docs/installation.md
docs/verification_api.md
docs/widget_api.md
package-lock.json
package.json
src/captcha.ts
src/dom.ts
src/headless.ts
src/html/custom-localization.html
src/html/index.html
src/localization.ts
src/main.ts
src/puzzle.ts
src/styles.css

This PR contains the changes for version 0.8.6, before merging and publishing it I would love to receive thumbs-up that this resolves #25.
The error message now spans two lines, with a clickable link in case of a fetch error. Errors are printed in the console to allow for debugging - they are not shown to the end user. There are still some errors that are not localized, I'm not sure if they are worth chasing (i.e. errors with a wrong sitekey, these should be easy to resolve before shipping your website to end users).
* Improvement to compatibility with SSR (thank you @fdeberle)
* Minor improvements to retry behavior in case of complete connection failure.

Localized, friendlier errors. Easier use in SSR frameworks (e.g. Gatsby)

---

rollup.library.config.ts

This PR fixes current typescript issue, where package.json have `types` property set to `friendly-challenge.d.ts` but rollup config outputs `friendly-captcha.d.ts`. This should be fixed in order for consumers of modules to not have broken TS.

Fix name of output file generated

---

src/types.ts
src/worker.ts
src/workergroup.ts

This PR improves the multithreading approach introduced in #63 by balancing the load more evenly between the worker threads. Instead of making each worker responsible for solving a fixed number of puzzles, each worker only receives a single puzzle at the a time and receives a new one as soon as it's done with the last one. This way the solving process is no longer (or at least less) bottlenecked by the slowest worker.
Depending on the difficulty of the puzzle this leads to speed gains of around 10-20% and should reduce the variance between "lucky" and "unlucky" solving attempts. It still produces the same exact same solution as the old implementation.
Internal Changes:
- Added an array to the workergroup which contains the workers that are ready to solve a puzzle (this also replaces …

Improve balancing the work between web workers

---

src/styles.css

This change prevents that captcha widgets extend beyond their container on small screens, while the same width as before is used on large screens.
I tested it with IE11, Firefox 97.0.1 (64-Bit) and Chrome 98.0.4758.102 for the widgets given in the index.html file.
250px seems to be a good min-width (at least for the default samples in index.html).
However, the texts are anyways scrollable in case custom texts or longer texts are used.
I kept the original width as max-width to keep the width as-is for large-screens.
However, a larger max-width could be used instead, if you want to support longer custom texts.
As for browser support: min and max-width should be supported starting with IE7. See
https://caniuse.com/minmaxwh for more details.
Feel free to perform further testing before merging …

#85 Replaced fixed width style with min-width and max-width

---

docs/changelog.md
docs/widget_api.md
src/captcha.ts

With this PR it's no longer possible to start the same widget instance twice. This has been a problem when using `startMode: auto` or `startMode: focus` in combination with calling the `widget.start()` function manually. Mentioned in https://github.com/FriendlyCaptcha/friendly-challenge/issues/89#issuecomment-1057098154.
I have also updated the react and vue examples to use `widget.destroy()` instead of `widget.reset()` to cleanup the widget instance. I have described why this is necessary in https://github.com/FriendlyCaptcha/friendly-challenge/issues/89#issuecomment-1062932635.

Fix multi-start bugs

---

src/captcha.ts

In #90 I moved the `hasBeenStarted` check from the `init` to the `start` method without considering that the retry button is also calling `start`. This made the retry button unusable in basically all cases. 
To fix this I have moved setting `hasBeenStarted` after the initial checks and also reset `hasBeenStarted` in the two other places where the retry button is rendered. Actually calling `reset` shouldn't be necessary here, I'm just setting `hasBeenStarted` back to false.
As far as I can tell this fixes the issue for all start modes and for all cases where the retry button is rendered.
fixes #108

reset `hasBeenStarted` on puzzle get error

---

src/captcha.ts

follow up to https://github.com/FriendlyCaptcha/friendly-challenge/pull/112
Fixes regression bug where `hasBeenStarted` is not reset to `false` upon puzzle expiration.
fixes https://github.com/FriendlyCaptcha/friendly-challenge/issues/113

Reset `hasBeenStarted` in `expire()` method

---

src/captcha.ts

Add option `skipStyleInjection` to prevent synchronous appending of widget's `<style>` element to document `<head>`.
Potential solution for https://github.com/FriendlyCaptcha/friendly-challenge/issues/114

Add option to skip script injection

---

src/puzzle.ts

When an error occurs in fetching or parsing the puzzle response body it was not really possible to introspect the error programmatically without ugly hacks. This adds the raw error under a new `.rawError` field.
In the past update we added a bit more error logging (some `console.error` when an error is thrown), along with this it should be easier to debug issues.

Return raw error in error callback

---

docs/widget_api.md

Calling `widget.destroy` in the `useEffect` cleanup causes issues with React 18 strict mode. In dev mode each component is unmounted and mounted twice to enforce best-practices. When `widget.destroy` is called the element is removed from the DOM which makes it impossible to render a new widget when the component mounts again.
#145

Fix react example

---

docs/openapi_spec.md

Depending on how docsify translates the markdown this might still not work, but we'll see :)

Fix OpenAPI urls

---

docs/installation.md

Link to the JS source files for self-hosting https://github.com/FriendlyCaptcha/friendly-challenge/issues/143

Download and self-host the widget library (releases)

---

src/localization.ts

Traditional Chinese language uses `zh_TW` key but `WidgetInstance` normalizes languages to lowercase here:
https://github.com/FriendlyCaptcha/friendly-challenge/blob/ef9d0f53df4788d7452d7b247ae5a4af48471d17/src/captcha.ts#L98
So the language is never found.
This changes the key to lowercase. I'm not sure if some B/C needs to be maintained here. If so, a new key should be added instead of old one being renamed.

Fix Chinese (Traditional)

---

src/localization.ts

The longer version of `button_start` from #172 did not fit.
closes #172

Fix french translation

---

docs/browser_support.md
docs/changelog.md
docs/flutter.md
docs/installation.md
docs/legacy_endpoint.md
package-lock.json
package.json
src/headless.ts
src/puzzle.ts

In some rare cases (less than one in a million?) the `navigator.plugins` prototype check would flag real users' browsers as headless. This release removes that check.

Remove plugins prototype check, prepare version 0.9.10

---

src/localization.ts

Ellipses should always have three dots. Seeing the two dots on our site really bugged me out, so here's a PR.
Ref: https://en.wikipedia.org/wiki/Ellipsis
I also cross-checked for all the languages where I made changes.
I fixed a typo in the Romanian localisation as well (I'm a close-to-bilingual speaker of the language).
Cheers!

Typo fixes

---

docs/widget_api.md

Fix data-lang attribute typo from "lt" to "lv"

Docs: fix typo in widget api docs

---

docs/changelog.md
docs/widget_api.md
src/dom.ts
src/html/index.html

You can now pass `"-"` for the `solution-field-name`/`solutionFieldName` option, then no hidden form field will be present whatsoever. Related to #216

Feature: Add option that allows for removing hidden form field entirely

---

docs/widget_api.md

This PR switches `watch` approach to `onMounted` and `onUnmounted` hooks to properly clean up widget instance.
Otherwise it will not be cleared, because when `container` Ref is dead, the `watch` functionality is also dead and nothing happens.

Improve cleanup logic of Vue.js example

---

docs/changelog.md

Before:
After:
FYI @denagyantal (GH wouldn't allow me to set you as reviewer)

Fix missing changelog items in sidebar

---

src/headless.ts

With node 21 a navigator is implemented in node environment https://nodejs.org/de/blog/announcements/v21-release-announce#navigator-object-integration but `navigator.userAgent` is undefined.
closes #237

fix navigator being present in server side environment

---

src/captcha.ts

When a language code with a locale suffix is supplied, try falling back to the code without it. This allows using language codes like `'de-ch' ` or `'en-gb'`.

Allow language locale fallback

---

src/captcha.ts
src/worker.ts
src/workergroup.ts

In some rare cases when the worker group is started before all workers are ready (have compiled the WASM solver), the `ready` event is emitted after the `started` event. This causes the widget UI to be stuck in the ready state until the puzzle is solved.
To fix this I have added a promise which is resolved when the whole worker group is ready. This way the `start` method waits for the `ready` event.
Another approach would be to ignore all `started` events from workers until all workers are ready. I feel like this could have some side effects tho

Fix event order edge case
